"""Generated by scripts/sync-project-config.mjs. Edit template.config.json instead."""

PROJECT_VERSION = "0.3.0"
PROJECT_SLUG = "agent-template-lite"
PROJECT_NAME = "智能业务助手"
PROJECT_NAME_EN = "Agent Template Lite"
AGENT_ID = "business-demo-agent"
AGENT_NAME = "智能业务助手"
COOKIE_PREFIX = "agent_template"
