"use client";

import { FilePlus2, RefreshCw, Search, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { publicPath } from "@/lib/public-path";

interface KnowledgeItem { id: number; title: string; category: string; content: string; source: string; status: "DRAFT" | "PUBLISHED"; version: number; indexStatus: string; updatedAt: string }
const empty: Omit<KnowledgeItem, "id" | "version" | "indexStatus" | "updatedAt"> = { title: "", category: "业务知识", content: "", source: "业务运营", status: "DRAFT" };

export function KnowledgeManager() {
  const [items, setItems] = useState<KnowledgeItem[]>([]); const [editing, setEditing] = useState<Partial<KnowledgeItem> | null>(null); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const response = await fetch(publicPath("/api/knowledge"), { cache: "no-store" }); const body = await response.json(); if (response.ok) setItems(body.items || []); }
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => items.filter((item) => `${item.title}${item.category}${item.source}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const payload = { ...Object.fromEntries(new FormData(event.currentTarget)), id: editing?.id }; const response = await fetch(publicPath("/api/knowledge"), { method: editing?.id ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(body.message || "保存失败"); return; } setItems(body.items || []); setEditing(null); setMessage(body.indexing?.message || "知识已保存"); }
  async function reindex() { setBusy(true); const response = await fetch(publicPath("/api/knowledge"), { method: "PATCH" }); const body = await response.json().catch(() => ({})); setBusy(false); setItems(body.items || items); setMessage(body.indexing?.message || body.message || "索引请求已完成"); }
  return <><form className="filter-bar" onSubmit={(event) => event.preventDefault()}><label><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索标题、分类或来源" /></label><button type="button" className="secondary-command" onClick={() => void reindex()} disabled={busy}><RefreshCw size={16} />重建索引</button><button type="button" className="primary-command" onClick={() => setEditing(empty)}><FilePlus2 size={17} />新增知识</button></form><section className="section-block table-only"><div className="data-table knowledge-table"><div className="data-row data-head"><span>知识</span><span>分类</span><span>版本</span><span>发布</span><span>索引</span><span>更新时间</span></div>{visible.map((item) => <button className="data-row editable-row" key={item.id} onClick={() => setEditing(item)}><span><strong>{item.title}</strong><small>{item.source}</small></span><span>{item.category}</span><span>v{item.version}</span><span><i className={`state ${item.status === "PUBLISHED" ? "success" : "neutral"}`}>{item.status}</i></span><span><i className={`state ${item.indexStatus === "READY" ? "success" : "warning"}`}>{item.indexStatus}</i></span><span>{new Date(item.updatedAt).toLocaleString("zh-CN")}</span></button>)}</div></section>{message && <p className="toast-message">{message}</p>}{editing && <div className="drawer-layer"><button className="drawer-scrim" onClick={() => setEditing(null)} aria-label="关闭" /><aside className="drawer" role="dialog" aria-modal="true"><header><div><small>KNOWLEDGE DOCUMENT</small><h2>{editing.id ? "编辑知识" : "新增知识"}</h2></div><button className="icon-command" onClick={() => setEditing(null)} aria-label="关闭"><X size={18} /></button></header><form onSubmit={save}><div className="form-grid"><label className="full"><span>标题</span><input name="title" defaultValue={editing.title} required /></label><label><span>分类</span><input name="category" defaultValue={editing.category} required /></label><label><span>来源</span><input name="source" defaultValue={editing.source} required /></label><label><span>状态</span><select name="status" defaultValue={editing.status}><option value="DRAFT">草稿</option><option value="PUBLISHED">发布</option></select></label><label className="full"><span>正文</span><textarea name="content" defaultValue={editing.content} rows={16} required /></label></div>{message && <p className="form-error">{message}</p>}<footer><button type="button" className="secondary-command" onClick={() => setEditing(null)}>取消</button><button className="primary-command" disabled={busy}>{busy ? "保存中..." : "保存"}</button></footer></form></aside></div>}</>;
}
