// Generated by scripts/sync-project-config.mjs. Edit template.config.json instead.
export const PROJECT_CONFIG = {
  version: "0.3.0",
  slug: "agent-template-lite",
  name: "智能业务助手",
  nameEn: "Agent Template Lite",
  agentId: "business-demo-agent",
  agentName: "智能业务助手",
  cookiePrefix: "agent_template",
  ports: { chat: 3000, console: 3001, agentos: 8000 },
} as const;

export const TEMPLATE_AGENT_ID = PROJECT_CONFIG.agentId;
