import { readFile, readdir, writeFile, rename } from "node:fs/promises";
import path from "node:path";

export const ROOT = path.resolve(import.meta.dirname, "..");
const ignoredDirectories = new Set([".git", ".next", ".venv", "node_modules", "var"]);
const textExtensions = /\.(?:ts|tsx|js|mjs|json|md|py|toml|ya?ml|lock|service|conf|env)$/;

export async function readProjectConfig(root = ROOT) {
  const value = JSON.parse(await readFile(path.join(root, "template.config.json"), "utf8"));
  validateProjectConfig(value);
  return value;
}

export function validateProjectConfig(value) {
  const requiredStrings = ["templateId", "templateVersion", "mode", "projectSlug", "projectName", "projectNameEn", "packageScope", "cookiePrefix"];
  for (const key of requiredStrings) {
    if (typeof value?.[key] !== "string" || !value[key].trim()) throw new Error(`template.config.json 缺少 ${key}`);
  }
  if (value.schemaVersion !== 1) throw new Error("不支持的 template.config schemaVersion");
  if (!/^[a-z][a-z0-9-]*$/.test(value.projectSlug)) throw new Error("projectSlug 必须是小写 ASCII kebab-case");
  if (!/^@[a-z][a-z0-9-]*$/.test(value.packageScope)) throw new Error("packageScope 必须是 @scope 格式");
  if (!/^[a-z][a-z0-9-]*$/.test(value.agent?.id || "")) throw new Error("agent.id 必须是小写 ASCII kebab-case");
  if (!value.agent?.name?.trim()) throw new Error("agent.name 不能为空");
  if (!Array.isArray(value.agent?.tools)) throw new Error("agent.tools 必须是数组");
  for (const tool of value.agent.tools) {
    if (!/^[a-z][a-z0-9_]*$/.test(tool?.name || "")) throw new Error("agent.tools.name 必须是 snake_case ASCII");
    if (tool.kind === "action" && tool.requiresConfirmation !== true) throw new Error(`有后果的 Tool ${tool.name} 必须 requiresConfirmation=true`);
  }
  if (!/^[a-z][a-z0-9_]*$/.test(value.database?.name || "")) throw new Error("database.name 必须是安全的 MySQL 标识符");
  for (const name of ["chat", "console", "agentos"]) {
    const port = value.defaultPorts?.[name];
    if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error(`defaultPorts.${name} 无效`);
  }
  if (!Array.isArray(value.capabilities) || !value.capabilities.length) throw new Error("capabilities 不能为空");
  return value;
}

export function generatedTypeScript(config) {
  return `// Generated by scripts/sync-project-config.mjs. Edit template.config.json instead.\nexport const PROJECT_CONFIG = {\n  version: ${JSON.stringify(config.templateVersion)},\n  slug: ${JSON.stringify(config.projectSlug)},\n  name: ${JSON.stringify(config.projectName)},\n  nameEn: ${JSON.stringify(config.projectNameEn)},\n  agentId: ${JSON.stringify(config.agent.id)},\n  agentName: ${JSON.stringify(config.agent.name)},\n  cookiePrefix: ${JSON.stringify(config.cookiePrefix)},\n  ports: { chat: ${config.defaultPorts.chat}, console: ${config.defaultPorts.console}, agentos: ${config.defaultPorts.agentos} },\n} as const;\n\nexport const TEMPLATE_AGENT_ID = PROJECT_CONFIG.agentId;\n`;
}

export function generatedPython(config) {
  return `\"\"\"Generated by scripts/sync-project-config.mjs. Edit template.config.json instead.\"\"\"\n\nPROJECT_VERSION = ${JSON.stringify(config.templateVersion)}\nPROJECT_SLUG = ${JSON.stringify(config.projectSlug)}\nPROJECT_NAME = ${JSON.stringify(config.projectName)}\nPROJECT_NAME_EN = ${JSON.stringify(config.projectNameEn)}\nAGENT_ID = ${JSON.stringify(config.agent.id)}\nAGENT_NAME = ${JSON.stringify(config.agent.name)}\nCOOKIE_PREFIX = ${JSON.stringify(config.cookiePrefix)}\n`;
}

export async function syncGeneratedProjectFiles(root, config, check = false) {
  const outputs = new Map([
    ["packages/shared/src/project-config.ts", generatedTypeScript(config)],
    ["services/agentos/app/project_config.py", generatedPython(config)],
  ]);
  const changed = [];
  for (const [relative, expected] of outputs) {
    const target = path.join(root, relative);
    const current = await readFile(target, "utf8").catch(() => "");
    if (current === expected) continue;
    changed.push(relative);
    if (!check) await writeFile(target, expected, "utf8");
  }
  return changed;
}

export async function textFiles(root = ROOT, directory = root) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (ignoredDirectories.has(entry.name)) continue;
    const target = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await textFiles(root, target));
    else if (textExtensions.test(entry.name) || entry.name === ".env.example") files.push(target);
  }
  return files;
}

export async function renameProjectPaths(root, oldSlug, newSlug) {
  const paths = await textFiles(root);
  const candidates = paths.filter((target) => path.basename(target).includes(oldSlug)).sort((a, b) => b.length - a.length);
  for (const target of candidates) {
    await rename(target, path.join(path.dirname(target), path.basename(target).replaceAll(oldSlug, newSlug)));
  }
}
